import type {
  FigureAlignment,
  HumanCatalogEntry,
  HumanCatalogId,
} from '../domain/catalog.ts'
import { heightMm } from '../domain/measure.ts'

const ALIGNMENT: FigureAlignment = { up: 'y', forward: 'z', soleY: 0 }

export const HUMAN_CATALOG: readonly HumanCatalogEntry[] = [
  {
    id: 'female-slim',
    label: 'Ari',
    subtitle: 'Female · lean frame',
    sex: 'female',
    referenceHeightMm: heightMm(1680),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'female',
      build: 'slim',
      shoulderWidth: 0.35,
      hipWidth: 0.34,
      torsoDepth: 0.2,
      inseamRatio: 0.49,
      headRatio: 0.132,
      stance: 0.13,
      hair: 'bob',
      skinHex: '#b9785e',
      clothingHex: '#355863',
      accentHex: '#d8a061',
      hairHex: '#2b211d',
    },
  },
  {
    id: 'female-athletic',
    label: 'Mika',
    subtitle: 'Female · athletic frame',
    sex: 'female',
    referenceHeightMm: heightMm(1720),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'female',
      build: 'athletic',
      shoulderWidth: 0.4,
      hipWidth: 0.35,
      torsoDepth: 0.23,
      inseamRatio: 0.5,
      headRatio: 0.126,
      stance: 0.16,
      hair: 'bun',
      skinHex: '#85533f',
      clothingHex: '#833d32',
      accentHex: '#e1b07e',
      hairHex: '#171312',
    },
  },
  {
    id: 'female-heavy',
    label: 'Sloane',
    subtitle: 'Female · full frame',
    sex: 'female',
    referenceHeightMm: heightMm(1660),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'female',
      build: 'heavy',
      shoulderWidth: 0.4,
      hipWidth: 0.43,
      torsoDepth: 0.31,
      inseamRatio: 0.45,
      headRatio: 0.134,
      stance: 0.18,
      hair: 'wave',
      skinHex: '#d5a27e',
      clothingHex: '#5c4e6f',
      accentHex: '#d7bd83',
      hairHex: '#6b3e2a',
    },
  },
  {
    id: 'male-slim',
    label: 'Luca',
    subtitle: 'Male · lean frame',
    sex: 'male',
    referenceHeightMm: heightMm(1790),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'male',
      build: 'slim',
      shoulderWidth: 0.4,
      hipWidth: 0.31,
      torsoDepth: 0.21,
      inseamRatio: 0.5,
      headRatio: 0.126,
      stance: 0.15,
      hair: 'crop',
      skinHex: '#e0aa82',
      clothingHex: '#38486b',
      accentHex: '#a8b7c7',
      hairHex: '#4a2b21',
    },
  },
  {
    id: 'male-athletic',
    label: 'Miles',
    subtitle: 'Male · athletic frame',
    sex: 'male',
    referenceHeightMm: heightMm(1830),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'male',
      build: 'athletic',
      shoulderWidth: 0.49,
      hipWidth: 0.34,
      torsoDepth: 0.27,
      inseamRatio: 0.49,
      headRatio: 0.122,
      stance: 0.19,
      hair: 'fade',
      skinHex: '#5f3d30',
      clothingHex: '#2d6254',
      accentHex: '#c68a4d',
      hairHex: '#141211',
    },
  },
  {
    id: 'male-heavy',
    label: 'Owen',
    subtitle: 'Male · broad frame',
    sex: 'male',
    referenceHeightMm: heightMm(1760),
    alignment: ALIGNMENT,
    recipe: {
      sex: 'male',
      build: 'heavy',
      shoulderWidth: 0.5,
      hipWidth: 0.43,
      torsoDepth: 0.34,
      inseamRatio: 0.45,
      headRatio: 0.128,
      stance: 0.21,
      hair: 'close',
      skinHex: '#9a684e',
      clothingHex: '#5a5a38',
      accentHex: '#c8a46a',
      hairHex: '#29211e',
    },
  },
]

export function humanEntry(id: HumanCatalogId): HumanCatalogEntry {
  const entry = HUMAN_CATALOG.find((candidate) => candidate.id === id)
  if (!entry) {
    throw new RangeError(`Unknown human catalog id: ${id}`)
  }

  return entry
}
